### ISSUE TITLE
Add support for Python3.8, including binary wheel

### ISSUE THREAD

**Issue by shirayu** [wbolster/plyvel#108]
Would you publish a wheel for python3.8 ?
(Related to #78, #79)

**Comment by wbolster** [comment]
yes, i should look into python 3.8 support for the wheels.

and both leveldb and snappy have new point releases so the wheels need to use those as well.

thanks for the nudge, i'll look into it later and will use this issue to report back.

**Comment by wbolster** [comment]
CI now also builds against python3.8: https://github.com/wbolster/plyvel/pull/109

**Comment by wbolster** [comment]
#111 bumps the snappy and leveldb deps

**Comment by wbolster** [comment]
plyvel 1.2.0 with python3.8 wheels is now on pypi: https://pypi.org/project/plyvel/1.2.0/

:rocket:

**Comment by wbolster** [comment]
changelog at https://plyvel.readthedocs.io/en/latest/news.html
