### ISSUE TITLE
Calling clear() after WriteBatch.write() ?

### ISSUE THREAD

**Issue by ixje** [wbolster/plyvel#120]
On a WriteBatch, should one call `clear()` after a `write()` or is that done implicitly when `write()`ing? Thanks

**Comment by wbolster** [comment]
i'm not entirely sure how leveldb operates internally, but generally you should just throw the `WriteBatch` instance away after you're done with it, and create a new one. the context manager support makes this easy, since there is no need to call `.write()` at all:

``` python
with db.write_batch() as wb:
    for i in xrange(100000):
        wb.put(bytes(i), bytes(i) * 100)
```

**Comment by ixje** [comment]
Thanks
