### ISSUE TITLE
Python Kernel Restarts when using Plyvel

### ISSUE THREAD

**Issue by hudefect** [wbolster/plyvel#122]
I am trying to use Plyvel but the kernel restarts every time I try to create a new DB.

Here is what I did:

- Fresh environment created with Anaconda
- pip install plyvel

Code I am trying to run:

```
import plyvel
db = plyvel.DB('/tmp/testdb/', create_if_missing=True)
```

Error message I get from JypyteLab:

```
Kernel Restarting
The kernel for xxx appears to have died. It will restart automatically.
```

Appreciate if anyone can point me in the right direction to get this sorted.

I have already tried restarting everything / creating a new environment / executing the same from console.

**Comment by wbolster** [comment]
i fear this lacks relevant information. do you have more error details, or stack traces?
