### ISSUE TITLE
Plyvel cannot open leveldb folder

### ISSUE THREAD

**Issue by sursu** [wbolster/plyvel#123]
I am trying to recover some data from erased google-chrome files on Ubuntu.

I have copied the recovered files (using TestDisk) to an external drive and tried to access the `leveldb` folder, but that results in an ```Invalid argument: /path/leveldb: does not exist``` error, as shown below:

![image](https://user-images.githubusercontent.com/12001304/109686017-2912e080-7b82-11eb-8078-194032c2c37b.png)

I first list the contents of the folder using the `%ls /path/` command. This shows that the folder can be read. But, somehow plyvel does not identify it.

I have copied the existing `leveldb` folder (newly created after reinstalling Chrome) to another drive and managed to access this folder. So the command I'm using appears to be correct.

What could be the issue?

**Comment by wbolster** [comment]
🤔 try a linux filesystem eg ext4 or ramdisk. practically, just copy into /tmp and try again.

(this is not plyvel specific, the error comes from leveldb itself)
