### ISSUE TITLE
Huge amounts of errors when trying to install Plyvel in a venv

### ISSUE THREAD

**Issue by visusys** [wbolster/plyvel#136]
Hi,

I'm trying to install Plyvel on Windows 10, Python 3.10.0. I am getting all sorts of errors during installation. Here's a screenshot:

![7YlWTe7 1](https://user-images.githubusercontent.com/33441569/141874770-24d2096f-39a0-499e-9b0e-78019607fa98.png)

Going to attach a full log as well.

[Log from Terminal.txt](https://github.com/wbolster/plyvel/files/7542458/Log.from.Terminal.txt)

Any help at all would be extremely appreciated!

**Comment by wbolster** [comment]
leveldb is not installed

```
    plyvel/_plyvel.cpp(632): fatal error C1083: Cannot open include file: 'leveldb/db.h': No such file or directory
```

**Comment by wbolster** [comment]
see #60
