### ISSUE TITLE
Python 3.10 Support

### ISSUE THREAD

**Issue by justincpresley** [wbolster/plyvel#138]
I really have like using ``plyvel``; but in one of my projects, I am unable to use it as it is coded in 3.10.

Is it known whether or not 3.10 support will be added in plyvel version 1.4 or 1.5?

**Comment by wbolster** [comment]
plyvel works fine on 3.10 afaik. more details please 

there are no binary wheels since it didn't exist at the time of the last release.

(i ran into some issues with trying to build new wheels using newer versions of python and c libraries, and lost interest at that time)

**Comment by wbolster** [comment]
hey @justincpresley i've just published a new version with python3.10 wheels. please give it a spin and let me know if this works for you 

https://plyvel.readthedocs.io/en/latest/news.html

**Comment by justincpresley** [comment]
Hi @wbolster, tested it out and it works as expected. Very much appreciated!

**Comment by wbolster** [comment]
cool, good luck!

fwiw, i built the wheels using leveldb 1.22 since 1.23 gives linking errors that i don't want to solve right now
