### ISSUE TITLE
I want to build the table-2.4.0.tar.gz dependented the library plyvel/comparator.cpp

### ISSUE THREAD

**Issue by honghh2018** [wbolster/plyvel#139]
Hi developer,
     I want to build the old tables-2.4.0 by myself, but when i run python2 setup.py, it show me the plyvel/comparator.cpp.
  and how can i fix it.

any advice would be appreciated.

Best
Hanhuihong

**Comment by wbolster** [comment]
you need to provide more detailed information on what you tried and what the result was 

i don't know what the "table" package is.

also python 2 is end of life and unsupported

**Comment by honghh2018** [comment]
Hi, 
    Sorry for the obscure description.
     
I download your plyvel library into my local directory through git clone.
and then build the python module tables-2.4.0
tar zxf tables-2.4.0.tar.gz && cd tables-2.4.0
python2 setup.py install --install-lib=/software/mini_conda/Miniconda3/lib/
![image](https://user-images.githubusercontent.com/41668708/148384254-1cb7d43f-c421-495c-a446-801fb8af7f28.png)

The error lying below:

building 'plyvel._plyvel' extension
C compiler: gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC

compile options: '-I/software/mini_conda/Miniconda3/include -I/software/mini_conda/Miniconda3/envs/SPRING_dev1/include/python2.7 -c'
extra options: '-Wall -g'
gcc: plyvel/comparator.cpp
cc1plus: 警告：command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
plyvel/comparator.cpp:10:10: 致命错误：slice.h：没有那个文件或目录
 #include <slice.h>
          ^~~~~~~~~
编译中断。
cc1plus: 警告：command line option ‘-Wstrict-prototypes’ is valid for C/ObjC but not for C++
plyvel/comparator.cpp:10:10: 致命错误：slice.h：没有那个文件或目录
 #include <slice.h>
          ^~~~~~~~~
编译中断。
error: Command "gcc -pthread -fno-strict-aliasing -g -O2 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/software/mini_conda/Miniconda3/include -I/software/mini_conda/Miniconda3/envs/SPRING_dev1/include/python2.7 -c plyvel/comparator.cpp -o build/temp.linux-x86_64-2.7/plyvel/comparator.o -Wall -g" failed with exit status 1

how can i get through this issue?
Best
Hanhuihong

**Comment by wbolster** [comment]
- i still have no idea what ‘tables-2.4.0’ is. you did not provide any links to what that project is. it's _not_ plyvel. 
- python 2 is _NOT_ supported. you should _NOT_ use it anymore. plyvel dropped python2 support over a year ago
- chinese error messages are not very helpful to me unfortunately. 
gtranslate tells me that ‘没有那个文件或目录’ means ‘no such file or directory’, and it seems you don't have leveldb development headers:

my advice:

- use python 3. python 2 is dead.
- install plyvel using wheels
- alternatievly, install leveldb development headers, and compile plyvel yourself.
