### ISSUE TITLE
read-only mode

### ISSUE THREAD

**Issue by mrx23dot** [wbolster/plyvel#147]
A read_only=True parameter would be nice during DB opening.
All it would do is give exception when someone tries to write the db. e.g. db.put(new)

Imagine you have high value read only data and you don't want sw bug destroying it, and manually restore it from backup.

it wouldn't have any resource overhead unlike snapshot. (i think that still modifies the db)
Maybe check it before writing buffer to disk not for each put().

As far as I know reading the leveldb doesn't modify it's content.

**Comment by wbolster** [comment]
leveldb does not have api for this afaik.

and i am not sure you're right. i think compaction (write operation) might still happen
