### ISSUE TITLE
Support for Python 3.11 in binary wheels

### ISSUE THREAD

**Issue by potiuk** [wbolster/plyvel#148]
I know it is eaarly (Python 3.11 has just been released yesterday) but we are hoping in Apache Airflow to a much faster cycle of adding new Python releases - especially that Pyhon 3.11 introduces huge performance improvements (25% is the average number claimed) due to a very focused effort to increase single-threaded Python performance (Specialized interpreter being the core of it but also many other improvements) without actually changing any of the Python code.

I'd appreciate if we can have binary releaases for Python 3.11. It's generally not easy to compile Plyvel from scratch so we release it 

I just opened such PR in Apache Airflow yesterday and plan to keep it open until it gets green :). So far plyvel had to be excluded there.

https://github.com/apache/airflow/pull/27264

I think it would be fantastic if we could as the open source community migrate to the new Python much faster.

Looking forward to cooperation on that one :)

**Comment by wbolster** [comment]
check out https://pypi.org/project/plyvel/1.5.0/ and https://plyvel.readthedocs.io/en/latest/news.html#plyvel-1-5-0

> Rebuild Linux wheels, with manylinux_2_17 and manylinux2014 compatibility (x86_64 only). Also produce Python 3.11 wheels. Still using Snappy 1.1.9 and LevelDB 1.22.

**Comment by wbolster** [comment]
oh, and if you're wondering why only x86_86, why only manylinux_2_17 and manylinux2014, etc.

i know i know i know 😫  but

https://github.com/wbolster/plyvel/commit/f1984253c88c35c130c46252183d6a68206eb5c1

**Comment by potiuk** [comment]
Cool. yeah. We already exclude plyvel from MacOS images/builds. That's not a problem.

**Comment by potiuk** [comment]
Thanks a bunch for quick reaction!

**Comment by wbolster** [comment]
you're welcome.

issues phrased like this one are a million times better than the usual ‘why you no make work on windows and mac 😠’ disregarding the complexity of all that stuff

and this was only a bit of work, so i thought… if not now then when 🙃

**Comment by potiuk** [comment]
Oh yeah. the time is NOW
