### ISSUE TITLE
leveldb created from large batch writes grows too much from 'compacting'

### ISSUE THREAD

**Issue by qrdlgit** [wbolster/plyvel#154]
I have a large leveldb created by plyvel using reasonably large batch writes.

I've copied it over to a new system for get only purposes - no writes / puts.

I use code like this:

```
db = plyvel.DB('./db.lvl', create_if_missing=True)
for enum_i,(k,v) in enumerate(db):
    kd = k.decode("utf-8") 
    vd = json.loads(v.decode("utf-8")) 
```

While iterating in this manner it has grown from 7GB to over 14GB, adding 100s of new files in the process.  Maybe this is 'compacting', but it's threatening to use up all the limited space I have in that particular location, and it seems a bit unreasonable considering I'm just doing get calls.

Is it because I'm enumerating the data? 

My work around is to treat it in batches, deleting everything and copying from over the entire database after each batch.  Crazy, but I see no alternative.

**Comment by wbolster** [comment]
not sure why this happens.

try compacting the db perhaps?

this is not a plyvel behaviour btw, but a leveldb thing, so maybe you can find other avenues with more knowledgeable people… curious to learn more though 🙃

**Comment by qrdlgit** [comment]
```
>>> import plyvel
>>> db = plyvel.DB("./db_copy.lvl")
>>> db.compact_range()
```

Just keeps growing and growing... sigh.  Already gone from 51 files to 705, and 'du' reports 7603876 -> 9256684

**Comment by qrdlgit** [comment]
Note:  I re-ran this on a separate system with more storage space and at the end of the compaction, it ended up OK.    3704 files, however.  

But it blew up all my storage space on the limited space system.   

So, lesson learned - make sure you compact before copying to a limited storage space for usage.

**Comment by wbolster** [comment]
you could also try increasing the block size. see notes about that here, which mention bulk scans explicitly:

https://github.com/google/leveldb/blob/main/doc/index.md
