### ISSUE TITLE
performance benchmarks

### ISSUE THREAD

**Issue by oleiade** [wbolster/plyvel#2]
I've submitted leveldb-cython to few benchmark tests using [Hurdles](http://github.com/oleiade/Hurdles); in order to see if it would be a good replacement for py-leveldb in [Elevator](http://github.com/oleiade/Elevator).

Here are the results, and the [bench case](https://gist.github.com/4051118):

**Nota** : Benchmarks are ran into a virtual machine run on one 3.5Ghz core and 4G ram, and virtual disk. So they don't mean to be a real world usage benchmark, but rather to give a comparison between the two libs on same testing environment.
Plus, hurdles has been run 3 times for each lib in order to have aricher sampling (leveldb performance greatly relies on current disk usage), but as a default hurdles runs every bench 10times (sampling).

**With py-leveldb**

``` bash

BenchLevelDB.bench_atomic_get ... 13.742 ms
BenchLevelDB.bench_atomic_put ... 28.224 ms
BenchLevelDB.bench_batch_mixed_put_delete ... 177.609 ms
BenchLevelDB.bench_batch_only_put ... 180.283 ms
BenchLevelDB.bench_range ... 33.658 ms

------------------------------------------------------------ 
Ran 5 benchmarks 

Done.

BenchLevelDB.bench_atomic_get ... 13.974 ms
BenchLevelDB.bench_atomic_put ... 25.984 ms
BenchLevelDB.bench_batch_mixed_put_delete ... 180.751 ms
BenchLevelDB.bench_batch_only_put ... 187.625 ms
BenchLevelDB.bench_range ... 34.347 ms

------------------------------------------------------------ 
Ran 5 benchmarks 

Done.

BenchLevelDB.bench_atomic_get ... 13.945 ms
BenchLevelDB.bench_atomic_put ... 26.036 ms
BenchLevelDB.bench_batch_mixed_put_delete ... 178.113 ms
BenchLevelDB.bench_batch_only_put ... 181.373 ms
BenchLevelDB.bench_range ... 33.568 ms

------------------------------------------------------------ 
Ran 5 benchmarks 

Done.% 
```

**with leveldb-cython**

``` bash

BenchLevelDB.bench_atomic_get ... 14.436 ms
BenchLevelDB.bench_atomic_put ... 25.468 ms
BenchLevelDB.bench_batch_mixed_put_delete ... 139.5 ms
BenchLevelDB.bench_batch_only_put ... 141.825 ms
BenchLevelDB.bench_range ... 116.309 ms

------------------------------------------------------------ 
Ran 5 benchmarks 

Done.

BenchLevelDB.bench_atomic_get ... 13.188 ms
BenchLevelDB.bench_atomic_put ... 25.35 ms
BenchLevelDB.bench_batch_mixed_put_delete ... 140.97 ms
BenchLevelDB.bench_batch_only_put ... 139.18 ms
BenchLevelDB.bench_range ... 114.635 ms

------------------------------------------------------------ 
Ran 5 benchmarks 

Done

BenchLevelDB.bench_atomic_get ... 12.902 ms
BenchLevelDB.bench_atomic_put ... 24.773 ms
BenchLevelDB.bench_batch_mixed_put_delete ... 140.039 ms
BenchLevelDB.bench_batch_only_put ... 143.598 ms
BenchLevelDB.bench_range ... 119.553 ms

------------------------------------------------------------ 
Ran 5 benchmarks 

Done.
```

Results interpretation:
- Atomic operations : equality
- Batches: leveldb-cython seems to be more performant in order of 15-20%
- Ranges : py-leveldb is doing far better 3-4x times faster. 

Let me know if you'd like other benchmarks to be added, or any recommandation on how I test each cases.

**Comment by wbolster** [comment]
first, this is a 10 year old closed ticket. no point discussing things here.

that said, it's up to the application using plyvel when to write a batch, and the api is similar to the leveldb C/C++ api, so this is totally up to the application.
