### ISSUE TITLE
Symbol not found: __ZN7leveldb2DB4OpenERKNS_7OptionsERKSsPPS0_ on Mavericks

### ISSUE THREAD

**Issue by varikin** [wbolster/plyvel#27]
Trying to get Plyvel working on Mavericks. I have LevelDB 1.15 installed via homebrew. In a Python 3.3 virtualenv, after `pip install plyvel`, I get the following:

```
Python 3.3.3 (default, Dec  4 2013, 09:48:34)
[GCC 4.2.1 Compatible Apple LLVM 4.2 (clang-425.0.28)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import plyvel
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "./plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(./plyvel/_plyvel.so, 2): Symbol not found:   __ZN7leveldb2DB4OpenERKNS_7OptionsERKSsPPS0_
  Referenced from: ./plyvel/_plyvel.so
  Expected in: flat namespace
 in ./plyvel/_plyvel.so 
```

The docs say to ensure the linker can find the shared library, but I am not sure how to do that with pip. When grepping for that symbol, I find something similar, but not exact. Is this a version mismatch or I am just not looking at the right things?

```
nm /usr/local/lib/libleveldb.1.dylib | grep __ZN7leveldb2DB4Open
0000000000009456 T __ZN7leveldb2DB4OpenERKNS_7OptionsERKNSt3__112basic_stringIcNS4_11char_traitsIcEENS4_9allocatorIcEEEEPPS0_
```

**Comment by pinkplus** [comment]
I encountered the same problem. It looks to me that the problem is caused by different C++ standard libraries used by leveldb and plyvel.

When I install leveldb (in the standard way, `make`), it is linked to libc++, which is the default standard library on OS X.
However, when I install plyvel, it is linked to libstdc++ for some unknown reason.
The name mangling is different for two libraries.

This command worked for me:

    CFLAGS='-mmacosx-version-min=10.7 -stdlib=libc++' pip install plyvel

**Comment by orsharir** [comment]
I've encountered this issue as well, and so far can't find a solution. If plyvel relies on LD_LIBRARY_PATH, then you should know that on OS X El Capitan you can no longer use that due to possible security restrictions by the OS. I've seen this in other open-source projects that relies on this flag for loading libraries (e.g. see https://github.com/BVLC/caffe/issues/3227).

**Comment by wbolster** [comment]
i cannot reproduce this.

on osx el capitan with homebrew I can build/run plyvel just fine on different python versions after i `brew install leveldb`. the test suite passes; relevant snippets from the `tox` output:

```
  py26: commands succeeded
  py27: commands succeeded
  py33: commands succeeded
  py34: commands succeeded
```

**Comment by mitallast** [comment]
I have same problem on os x 10.11.3 with this commands:

    brew install leveldb
    pip install pyvel

pyvel package installed with wheels, so I try reinstall pyvel without wheels:

    pip uninstall pyvel
    CFLAGS='-mmacosx-version-min=10.7 -stdlib=libc++' pip install --no-use-wheel plyvel

Maybe something wrong with wheel package?

**Comment by wbolster** [comment]
plyvel does not provide wheel packages; those are built locally on your system by `pip` i think, so yeah, removing them from your local cache may help.

**Comment by flaviovdf** [comment]
Had the same issue, got it working by doing:

```
pip uninstall plyvel
CFLAGS='-mmacosx-version-min=10.7 -stdlib=libc++' pip reinstall plyvel --no-cache-dir```

The `--no-cache-dir`` was needed, if it is not provided, pip will re-use the previous compilation.

**Comment by ysunf** [comment]
@flaviovdf 
His answer works for me. 👍 
I install leveldb with homebrew, and install plyvel with pip.
when i test "$python -c 'impott plyvel'", it comes up the same 'Symbol' error.
So i uninstall plyvel and reinstall with : 
CFLAGS='-mmacosx-version-min=10.7 -stdlib=libc++' pip install plyvel --no-cache-dir

**Comment by troyoung** [comment]
Same problem on linux. I want to use commands like "CFLAGS='-mmacosx-version-min=10.7 -stdlib=libc++' pip install plyvel --no-cache-dir", but all failed

**Comment by wbolster** [comment]
@troyoung this is about a mac osx specific issue. please open a new issues with all relevant information if your problem persists.

**Comment by jakeywu** [comment]
https://cloud.tencent.com/developer/article/1815745

**Comment by jakeywu** [comment]
i have solved my problem by install leveldb@1.21 which default is @1.23

**Comment by jakeywu** [comment]
i have solved my problem by install leveldb@1.21 which default is @1.23

https://cloud.tencent.com/developer/article/1815745

**Comment by kobiebotha** [comment]
@jakeywu  Unfortunately 1.21 does not work Apple Sillicon

**Comment by ManuelSchneid3r** [comment]
Has anybody found an easy solution to this? Still an issue under ventura 13.2, leveldb 1.23, plyvel 1.5

**Comment by abhi-jha** [comment]
Yeah, this doesn't work on MacOS Sonoma 14.2.1. 

I have installed leveldb on a custom path using : https://github.com/wbolster/plyvel/blob/main/scripts/install-leveldb.sh

I have a new path where both lib/ and include/ folders are available. I included these paths when running make which successfully generates the .so object. 

Now when I install the libray itself using `pip install .`, it installs successfully. But when I import it into a file it tell me the following :

```
Traceback (most recent call last):
  File "/path/temp/plyvel/leveldb_stuff.py", line 1, in <module>
    import plyvel
  File "/path/temp/plyvel/plyvel/__init__.py", line 6, in <module>
    from ._plyvel import (  # noqa
ImportError: dlopen(/path/temp/plyvel/plyvel/_plyvel.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZTIN7leveldb10ComparatorE'
```

I am not sure if the lib path needs to be provided again somewhere. I mostly edited the `setup.py` file.

NOTE that `make` succeeded successfully and there is an .so file in the folder.

**Comment by Soulter** [comment]
> Yeah, this doesn't work on MacOS Sonoma 14.2.1.
> 
> I have installed leveldb on a custom path using : https://github.com/wbolster/plyvel/blob/main/scripts/install-leveldb.sh
> 
> I have a new path where both lib/ and include/ folders are available. I included these paths when running make which successfully generates the .so object.
> 
> Now when I install the libray itself using `pip install .`, it installs successfully. But when I do import it into a file it tells me the following :
> 
> ```
> Traceback (most recent call last):
>   File "/path/temp/plyvel/leveldb_stuff.py", line 1, in <module>
>     import plyvel
>   File "/path/temp/plyvel/plyvel/__init__.py", line 6, in <module>
>     from ._plyvel import (  # noqa
> ImportError: dlopen(/path/temp/plyvel/plyvel/_plyvel.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '__ZTIN7leveldb10ComparatorE'
> ```
> 
> I am not sure if the lib path needs to be provided again somewhere. I mostly edited the `setup.py` file.
> 
> NOTE that `make` succeeded successfully and there is an .so file in the folder.

Same problem here...

**Comment by abhi-jha** [comment]
I figured this out eventually. 

```
LDFLAGS="-L/path-to-lib-folder/lib" CFLAGS="-I/path-to-include-folder/include" make

pip install -e /path/to/python/package
```

The compilation of leveldb above will generate a lib folder with shared objects. You need to provide this at runtime for your python source to execute. The symbol error happens as the pyhton source is not able to find the generated shared object. 

Now, we also need the environment variable pointing to the DLL at runtime. This was missing when I made the comment earlier. 

Mac:

`DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/path-to-lib-folder python main.py
`

Unix:

`LD_LIBRARY_PATH=$LD_LIBRARY_PATH:/path-to-lib-folder pyhton main.py
`

This should be enough to execute the leveldb in python.
