### ISSUE TITLE
Compile LevelDB if not available

### ISSUE THREAD

**Issue by k4nar** [wbolster/plyvel#31]
Hi,
During the installation, Plyvel could try to compile LevelDB if it's not already installed. That's what PyZMQ is doing : 

> When compiling pyzmq (e.g. installing with pip on Linux), it is generally recommended    that zeromq be installed separately, via homebrew, apt, yum, etc. If this is not available, pyzmq will try to build libzmq as a Python Extension, though this is not guaranteed to work.

I think it would require quite a bit of work in order to work on a maximum of platform, but it would be a really great advantage for Plyvel. I'll try do to it, but I won't have much time in the next few days, so it might be in a while.

**Comment by wbolster** [comment]
i consider this ‘fixed’ for linux since i do provide ‘manylinux1’ wheels on pypi nowadays.

for other platforms i have no clue/experience, sorry.
