### ISSUE TITLE
Can't Install on OSX

### ISSUE THREAD

**Issue by ConceptPending** [wbolster/plyvel#34]
I've only used Plyvel on Linux before, and I'm having the following issues when trying to install on OSX.

```
plyvel/_plyvel.cpp:321:10: fatal error: 'leveldb/db.h' file not found

#include "leveldb/db.h"
```

I've installed LevelDB from source, and installing "pip install leveldb" gets me a working py-leveldb install, but I'd much rather use plyvel if I can get it working.

I've tried Googling every aspect of the issue possible, but at this point I've been on a wild goose chase for over a day now and am no closer to being able to use plyvel on OSX.

Thanks,

Nick

**Comment by bakavic** [comment]
Just wanted to drop a note - in OS X, it seems like `/usr/local/include`, where the leveldb headers (db.h) live, is not visible to gcc.

You need to install the Apple command line tools:

    xcode-select --install

plyvel will compile after that.

**Comment by wbolster** [comment]
... or use homebrew.

Victor Heng <notifications@github.com> schreef op 31 januari 2015 09:22:14 CET:
>Just wanted to drop a note - in OS X, it seems like
>`/usr/local/include`, where the leveldb headers (db.h) live, is not
>visible to gcc.
>
>You need to install the Apple command line tools:
>
>    xcode-select --install
>
>plyvel will compile after that.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wbolster/plyvel/issues/34#issuecomment-72309360

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by bakavic** [comment]
Hmm, I did use homebrew to install leveldb, but gcc still could not pick it up.

Is there any special thing I need to do apart from `brew install leveldb`?

**Comment by wbolster** [comment]
Not sure. I installed both the xcode stuff and homebrew...

**Comment by mahmoudimus** [comment]
@bakavic how I ended it up fixing it: `pip install --global-option=build_ext --global-option="-I/usr/local/include" --global-option="-L/usr/local/lib" Plyvel`

**Comment by wbolster** [comment]
see also #66 which seems similar btw

**Comment by PaulRBerg** [comment]
I tried all the suggestions in this issue and everything I found on the web, but I still get:

```
plyvel/_plyvel.cpp:589:10: fatal error: 'leveldb/db.h' file not found
#include "leveldb/db.h"
```

Opened an issue in this repo, but I think the bug is caused by `plyvel`.

https://github.com/omisego/plasma-mvp/issues/166

**Comment by wbolster** [comment]
@paulrberg that issue you linked to indicates that you got it working. it would've been nice if you mentioned that here as well, including the solution to your problem.

**Comment by PaulRBerg** [comment]
Hey @wbolster, I got it half-working, because I had to completely reinstall environment.  I was waiting for a reply from someone in that repo, to make sure it was just related to my python set up.

The "solution" was to erase all python executables in the os, install `pyenv`, `pyenv-virtualenv` and the versions I needed. `leveldb` had always been installed.

**Comment by wbolster** [comment]
@PaulRBerg ok, thanks! it was not a plyvel problem after all, then. :+1:
