### ISSUE TITLE
plyvel version 0.9 support levelDB 1.18?

### ISSUE THREAD

**Issue by rendykstan** [wbolster/plyvel#37]
@wbolster what's the latest version of levelDB you have tried with plyvel? I am still on 1.12. Wondering if I should upgrade.

**Comment by wbolster** [comment]
LevelDB 1.18 works fine, and in the past I've tried it with many other versions as well.

On OSX Yosemite, compilation and tests pass for all Python versions I have installed:

```
  py26: commands succeeded
  py27: commands succeeded
ERROR:   py32: InterpreterNotFound: python3.2
ERROR:   py33: InterpreterNotFound: python3.3
  py34: commands succeeded
```

using LevelDB 1.18:

```
$ brew info leveldb
leveldb: stable 1.18 (bottled)
```

I could produce similar results for Linux (but that machine is currently turned off).

**Comment by rendykstan** [comment]
Yes. I have tested it and it works!
