### ISSUE TITLE
when i kill the process and restart it, an error occurs init database error IO error: lock auth_times.db/LOCK: Resource temporarily unavailable

### ISSUE THREAD

**Issue by xiaochao** [wbolster/plyvel#41]
leveldb versio is 1.15.0
plyvel version is 0.9
centos 64bit python2.7

**Comment by wbolster** [comment]
This has nothing to do with Plyvel I think. LevelDB can be used from a single process only. Are you sure you're running only one process that accesses the database? Is you database on a local file system?

**Comment by xiaochao** [comment]
my database is on local file system.i running levelDB in webpy+uwsgi.I start three uwsgi process,one mater and two children.when i used uwsgi --reload command,leveldb report the error.

**Comment by wbolster** [comment]
only a single process can access a leveldb database at the same time. (this is unrelated to plyvel.) it looks like your setup does not adhere to this. try with a single process.


On November 2, 2015 6:23:24 AM GMT+01:00, simon <notifications@github.com> wrote:
>my database is on local file system.i running levelDB in webpy+uwsgi.I
>start three uwsgi process,one mater and two children.when i used uwsgi
>--reload command,leveldb report the error.
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wbolster/plyvel/issues/41#issuecomment-152918000


    — Wouter

-- 
Sent from my phone. Please forgive my tpyos.

**Comment by xiaochao** [comment]
got it.thanks
