### ISSUE TITLE
Setup VS2015 build Error

### ISSUE THREAD

**Issue by mo0feng** [wbolster/plyvel#43]
running install
running bdist_egg
running egg_info
writing dependency_links to plyvel.egg-info\dependency_links.txt
writing plyvel.egg-info\PKG-INFO
writing top-level names to plyvel.egg-info\top_level.txt
reading manifest file 'plyvel.egg-info\SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'doc\build\html'
warning: no files found matching 'plyvel\*.pxi'
writing manifest file 'plyvel.egg-info\SOURCES.txt'
installing library code to build\bdist.win-amd64\egg
running install_lib
running build_py
running build_ext
building 'plyvel._plyvel' extension
D:\Program Files\vs2015\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL /DNDEBUG /MD -IC:\Python35\include -IC:\Python35\include "-ID:\Program Files\vs2015\VC\INCLUDE" "-ID:\Program Files\vs2015\VC\ATLMFC\INCLUDE" "-IC:\Program Files
(x86)\Windows Kits\10\include\10.0.10150.0\ucrt" "-IC:\Program Files (x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files (x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files (x86)\Windows Kits\8.1\include\um" "-
IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc /Tpplyvel/_plyvel.cpp /Fobuild\temp.win-amd64-3.5\Release\plyvel/_plyvel.obj -Wall -g
cl: ??? warning D9002 :??????"-g"
_plyvel.cpp
c1xx: fatal error C1083: ???????: "plyvel/_plyvel.cpp": No such file or directory
error: command 'D:\\Program Files\\vs2015\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2

Python:3.5
OS:Windows 10 (64bit)
Setup: download(py setup.py) and pip install plyvel

**Comment by wbolster** [comment]
are you using a released tarball or git checkout? for the latter you need to run cython first. http://plyvel.readthedocs.org/en/latest/developer.html

On November 13, 2015 8:01:37 AM GMT+01:00, mo0feng <notifications@github.com> wrote:
>running install
>running bdist_egg
>running egg_info
>writing dependency_links to plyvel.egg-info\dependency_links.txt
>writing plyvel.egg-info\PKG-INFO
>writing top-level names to plyvel.egg-info\top_level.txt
>reading manifest file 'plyvel.egg-info\SOURCES.txt'
>reading manifest template 'MANIFEST.in'
>warning: no files found matching '*' under directory 'doc\build\html'
>warning: no files found matching 'plyvel\*.pxi'
>writing manifest file 'plyvel.egg-info\SOURCES.txt'
>installing library code to build\bdist.win-amd64\egg
>running install_lib
>running build_py
>running build_ext
>building 'plyvel._plyvel' extension
>D:\Program Files\vs2015\VC\BIN\amd64\cl.exe /c /nologo /Ox /W3 /GL
>/DNDEBUG /MD -IC:\Python35\include -IC:\Python35\include "-ID:\Program
>Files\vs2015\VC\INCLUDE" "-ID:\Program Files\vs2015\VC\ATLMFC\INCLUDE"
>"-IC:\Program Files
>(x86)\Windows Kits\10\include\10.0.10150.0\ucrt" "-IC:\Program Files
>(x86)\Windows Kits\NETFXSDK\4.6\include\um" "-IC:\Program Files
>(x86)\Windows Kits\8.1\include\shared" "-IC:\Program Files
>(x86)\Windows Kits\8.1\include\um" "-
>IC:\Program Files (x86)\Windows Kits\8.1\include\winrt" /EHsc
>/Tpplyvel/_plyvel.cpp
>/Fobuild\temp.win-amd64-3.5\Release\plyvel/_plyvel.obj -Wall -g
>cl: ??? warning D9002 :??????"-g"
>_plyvel.cpp
>c1xx: fatal error C1083: ???????: "plyvel/_plyvel.cpp": No such file or
>directory
>error: command 'D:\\Program Files\\vs2015\\VC\\BIN\\amd64\\cl.exe'
>failed with exit status 2
>
>
>Python:3.5
>OS:Windows 10 (64bit)
>Setup: download(py setup.py) and pip install plyvel 
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wbolster/plyvel/issues/43


    — Wouter

-- 
Sent from my phone. Please forgive my tpyos.

**Comment by mo0feng** [comment]
Yes,it is cpython(Python 3.5.0). 
I'm on the git checkout(master).

**Comment by wbolster** [comment]
i didn't ask about cpython. you need to run cython. this is only needed if developing plyvel itself using a git checkout. the recommended approach is to use a released version from pypi.python.org instead of using development checkouts.again, see the documentation...

On November 13, 2015 8:32:43 AM GMT+01:00, mo0feng <notifications@github.com> wrote:
>Yes,it is cpython(Python 3.5.0). 
>I'm on the git checkout(master).
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/wbolster/plyvel/issues/43#issuecomment-156354185


    — Wouter

-- 
Sent from my phone. Please forgive my tpyos.

**Comment by mo0feng** [comment]
Thank you very much, I use the PIP problem is encountered:

D:\>SET VS90COMNTOOLS=%VS140COMNTOOLS%

D:\>SET VS100COMNTOOLS=%VS140COMNTOOLS%

D:\>pip install plyvel
Collecting plyvel
  Using cached plyvel-0.9.tar.gz
Building wheels for collected packages: plyvel
  Running setup.py bdist_wheel for plyvel
  Complete output from command C:\Python34\python.exe -c "import setuptools;__file__='C:\\Users\\AppData\\Local\\Temp\\pip-build-zrc8p70e\\plyvel\\setup.py';exec(compile(open(__file__).read().replace('\r\n', '\n'), __fi
le__, 'exec'))" bdist_wheel -d C:\Users\AppData\Local\Temp\tmpy5k0rfphpip-wheel-:
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.4
  creating build\lib.win-amd64-3.4\plyvel
  copying plyvel\_version.py -> build\lib.win-amd64-3.4\plyvel
  copying plyvel\__init__.py -> build\lib.win-amd64-3.4\plyvel
  running build_ext
  building 'plyvel._plyvel' extension
  creating build\temp.win-amd64-3.4
  creating build\temp.win-amd64-3.4\Release
  creating build\temp.win-amd64-3.4\Release\plyvel
  D:\Program Files\vs2015\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python34\include -IC:\Python34\include /Tpplyvel/_plyvel.cpp /Fobuild\temp.win-amd64-3.4\Release\plyvel/_plyvel.obj -Wall -g
  cl: ??? warning D9002 :??????"-g"
  _plyvel.cpp
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\corecrt_io.h(49): warning C4820: "_finddata32i64_t":"4"??????? ????"_finddata32i64_t::name"?
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\corecrt_io.h(54): warning C4820: "_finddata64i32_t":"4"??????? ????"_finddata64i32_t::attrib"?
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\corecrt_io.h(64): warning C4820: "__finddata64_t":"4"??????? ????"__finddata64_t::attrib"?
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\corecrt_io.h(69): warning C4820: "__finddata64_t":"4"??????? ????"__finddata64_t::name"?
  C:\Program Files (x86)\Windows Kits\8.1\include\shared\basetsd.h(418): warning C4668: ???"_WIN32_WINNT"????????,?"0"??"#if/#elif"
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\time.h(35): warning C4820: "_timespec64":"4"??????? ????"_timespec64::tv_nsec"?
  C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\time.h(42): warning C4820: "timespec":"4"??????? ????"timespec::tv_nsec"?
  c:\python34\include\object.h(368): warning C4820: "_typeobject":"4"??????? ????"_typeobject::tp_flags"?
  c:\python34\include\object.h(412): warning C4820: "_typeobject":"4"??????? ????"_typeobject::tp_version_tag"?
  c:\python34\include\object.h(427): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::slot"?
  c:\python34\include\object.h(435): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::flags"?
  c:\python34\include\pytime.h(22): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::tv_usec"?
  c:\python34\include\pyhash.h(94): warning C4623: "<unnamed-tag>": ??????????,???????????????????
  c:\python34\include\pyhash.h(94): warning C4626: "<unnamed-tag>": ?????????,??????????????????
  c:\python34\include\pyhash.h(94): warning C5027: "<unnamed-tag>": ??????????????????,?????????????????
  c:\python34\include\bytearrayobject.h(30): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::ob_exports"?
  c:\python34\include\bytesobject.h(41): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::ob_sval"?
  c:\python34\include\unicodeobject.h(350): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::state"?
  c:\python34\include\unicodeobject.h(917): warning C4820: "<unnamed-tag>":"2"??????? ????"<unnamed-tag>::readonly"?
  c:\python34\include\longintrepr.h(92): warning C4820: "_longobject":"4"??????? ????"_longobject::ob_digit"?
  c:\python34\include\memoryobject.h(43): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::flags"?
  c:\python34\include\memoryobject.h(63): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::flags"?
  c:\python34\include\memoryobject.h(66): warning C4820: "<unnamed-tag>":"5"??????? ????"<unnamed-tag>::format"?
  c:\python34\include\methodobject.h(45): warning C4820: "PyMethodDef":"4"??????? ????"PyMethodDef::ml_flags"?
  c:\python34\include\pystate.h(85): warning C4820: "_ts":"2"??????? ????"_ts::recursion_critical"?
  c:\python34\include\pystate.h(105): warning C4820: "_ts":"4"??????? ????"_ts::gilstate_counter"?
  c:\python34\include\genobject.h(24): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::gi_running"?
  c:\python34\include\descrobject.h(29): warning C4820: "wrapperbase":"4"??????? ????"wrapperbase::offset"?
  c:\python34\include\descrobject.h(33): warning C4820: "wrapperbase":"4"??????? ????"wrapperbase::flags"?
  c:\python34\include\structseq.h(20): warning C4820: "PyStructSequence_Desc":"4"??????? ????"PyStructSequence_Desc::n_in_sequence"?
  c:\python34\include\pyerrors.h(18): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
  c:\python34\include\pyerrors.h(22): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
  c:\python34\include\pyerrors.h(32): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
  c:\python34\include\pyerrors.h(39): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
  c:\python34\include\pyerrors.h(48): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
  c:\python34\include\pyerrors.h(53): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
  c:\python34\include\pyerrors.h(65): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
  c:\python34\include\import.h(119): warning C4820: "_frozen":"4"??????? ????"_frozen::size"?
  c:\python34\include\code.h(18): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::co_flags"?
  c:\python34\include\code.h(29): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::co_firstlineno"?
  D:\Program Files\vs2015\VC\INCLUDE\xlocale(341): warning C4530: ??? C++ ??????,???????????? /EHsc
  plyvel/_plyvel.cpp(359): fatal error C1083: ????????: "leveldb/db.h": No such file or directory
  error: command 'D:\\Program Files\\vs2015\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2

  ----------------------------------------
←[31m  Failed building wheel for plyvel←[0m
Failed to build plyvel
Installing collected packages: plyvel
  Running setup.py install for plyvel
    Complete output from command C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\AppData\\Local\\Temp\\pip-build-zrc8p70e\\plyvel\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__fil
e__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\AppData\Local\Temp\pip-cwk_d8mt-record\install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    running build_py
    running build_ext
    building 'plyvel._plyvel' extension
    D:\Program Files\vs2015\VC\BIN\amd64\cl.exe /c /nologo /Ox /MD /W3 /GS- /DNDEBUG -IC:\Python34\include -IC:\Python34\include /Tpplyvel/_plyvel.cpp /Fobuild\temp.win-amd64-3.4\Release\plyvel/_plyvel.obj -Wall -g
    cl: ??? warning D9002 :??????"-g"
    _plyvel.cpp
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\corecrt_io.h(49): warning C4820: "_finddata32i64_t":"4"??????? ????"_finddata32i64_t::name"?
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\corecrt_io.h(54): warning C4820: "_finddata64i32_t":"4"??????? ????"_finddata64i32_t::attrib"?
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\corecrt_io.h(64): warning C4820: "__finddata64_t":"4"??????? ????"__finddata64_t::attrib"?
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\corecrt_io.h(69): warning C4820: "__finddata64_t":"4"??????? ????"__finddata64_t::name"?
    C:\Program Files (x86)\Windows Kits\8.1\include\shared\basetsd.h(418): warning C4668: ???"_WIN32_WINNT"????????,?"0"??"#if/#elif"
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\time.h(35): warning C4820: "_timespec64":"4"??????? ????"_timespec64::tv_nsec"?
    C:\Program Files (x86)\Windows Kits\10\include\10.0.10150.0\ucrt\time.h(42): warning C4820: "timespec":"4"??????? ????"timespec::tv_nsec"?
    c:\python34\include\object.h(368): warning C4820: "_typeobject":"4"??????? ????"_typeobject::tp_flags"?
    c:\python34\include\object.h(412): warning C4820: "_typeobject":"4"??????? ????"_typeobject::tp_version_tag"?
    c:\python34\include\object.h(427): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::slot"?
    c:\python34\include\object.h(435): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::flags"?
    c:\python34\include\pytime.h(22): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::tv_usec"?
    c:\python34\include\pyhash.h(94): warning C4623: "<unnamed-tag>": ??????????,???????????????????
    c:\python34\include\pyhash.h(94): warning C4626: "<unnamed-tag>": ?????????,??????????????????
    c:\python34\include\pyhash.h(94): warning C5027: "<unnamed-tag>": ??????????????????,?????????????????
    c:\python34\include\bytearrayobject.h(30): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::ob_exports"?
    c:\python34\include\bytesobject.h(41): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::ob_sval"?
    c:\python34\include\unicodeobject.h(350): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::state"?
    c:\python34\include\unicodeobject.h(917): warning C4820: "<unnamed-tag>":"2"??????? ????"<unnamed-tag>::readonly"?
    c:\python34\include\longintrepr.h(92): warning C4820: "_longobject":"4"??????? ????"_longobject::ob_digit"?
    c:\python34\include\memoryobject.h(43): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::flags"?
    c:\python34\include\memoryobject.h(63): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::flags"?
    c:\python34\include\memoryobject.h(66): warning C4820: "<unnamed-tag>":"5"??????? ????"<unnamed-tag>::format"?
    c:\python34\include\methodobject.h(45): warning C4820: "PyMethodDef":"4"??????? ????"PyMethodDef::ml_flags"?
    c:\python34\include\pystate.h(85): warning C4820: "_ts":"2"??????? ????"_ts::recursion_critical"?
    c:\python34\include\pystate.h(105): warning C4820: "_ts":"4"??????? ????"_ts::gilstate_counter"?
    c:\python34\include\genobject.h(24): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::gi_running"?
    c:\python34\include\descrobject.h(29): warning C4820: "wrapperbase":"4"??????? ????"wrapperbase::offset"?
    c:\python34\include\descrobject.h(33): warning C4820: "wrapperbase":"4"??????? ????"wrapperbase::flags"?
    c:\python34\include\structseq.h(20): warning C4820: "PyStructSequence_Desc":"4"??????? ????"PyStructSequence_Desc::n_in_sequence"?
    c:\python34\include\pyerrors.h(18): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
    c:\python34\include\pyerrors.h(22): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
    c:\python34\include\pyerrors.h(32): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
    c:\python34\include\pyerrors.h(39): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
    c:\python34\include\pyerrors.h(48): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
    c:\python34\include\pyerrors.h(53): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
    c:\python34\include\pyerrors.h(65): warning C4820: "<unnamed-tag>":"7"??????? ????"<unnamed-tag>::suppress_context"?
    c:\python34\include\import.h(119): warning C4820: "_frozen":"4"??????? ????"_frozen::size"?
    c:\python34\include\code.h(18): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::co_flags"?
    c:\python34\include\code.h(29): warning C4820: "<unnamed-tag>":"4"??????? ????"<unnamed-tag>::co_firstlineno"?
    D:\Program Files\vs2015\VC\INCLUDE\xlocale(341): warning C4530: ??? C++ ??????,???????????? /EHsc
    plyvel/_plyvel.cpp(359): fatal error C1083: ????????: "leveldb/db.h": No such file or directory
    error: command 'D:\\Program Files\\vs2015\\VC\\BIN\\amd64\\cl.exe' failed with exit status 2

    ----------------------------------------
←[31mCommand "C:\Python34\python.exe -c "import setuptools, tokenize;__file__='C:\\Users\\AppData\\Local\\Temp\\pip-build-zrc8p70e\\plyvel\\setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace
('\r\n', '\n'), __file__, 'exec'))" install --record C:\Users\AppData\Local\Temp\pip-cwk_d8mt-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\AppData
\Local\Temp\pip-build-zrc8p70e\plyvel←[0m

**Comment by mo0feng** [comment]
Pycharm:
![plyvel](https://cloud.githubusercontent.com/assets/9604557/11141589/bab34686-8a21-11e5-8644-a1754dec71df.png)

**Comment by wbolster** [comment]
it looks like you're missing the `leveldb` library and its development headers, on which plyvel depends (it's a wrapper for leveldb after all). i don't know anything about how to install libraries on windows systems, so i don't think i can be of any help on that front.

**Comment by wbolster** [comment]
Perhaps #31 provides some pointers for you (or people to ask)

**Comment by mo0feng** [comment]
Good,Thank you very much.
