### ISSUE TITLE
Implementation of __exit__ interface

### ISSUE THREAD

**Issue by leighton** [wbolster/plyvel#44]
I would like to use plyvel in a notebook development environment (ipython). Supporting a graceful close (i.e. lock release) between code evaluations using the `__exit__`  interface would be great for dynamic evaluation environments. I would make a pull request but I think this change is trivial and you'd have it done before breakfast :)

**Comment by wbolster** [comment]
hmm. i'm not sure what you want to achieve. note that iterators and write batches already implement the context manager protocol, meaning they can be used in a `with` block.

do you mean that you want to allow a `DB` instance to be used as a context manager? i don't see any use case for that...

additionally, i don't code before breakfast. ;)

**Comment by leighton** [comment]
```python
with plyvel.DB('./_db') as db:
  print db.get('key')
```

`__exit__` will close the "connection" and release the lock in the level db directory

Use case: long running processes that infrequently access the database where one wishes to close the connection to avoid contention.

**Comment by wbolster** [comment]
the `contextlib` module from the stdlib has a `closing()` context manager helper which might help here:

```python
from contextlib import closing

with closing(plyvel.DB('./_db') as db:
  print db.get('key')
```

alternatively you could write a context manager wrapper if you want more flexibility and less repetition in your code (e.g. no repeated db names). easiest way is to use `contextlib` again:

```python
from contextlib import contextmanager

@contextmanager
def magic_db():
    db = plyvel.DB('./_db')
    try:
        yield db
    finally:
        db.close()
```

...which can be used like this:

```python
with magic_db() as db:
    db.get(b'foo')
```

**Comment by tlevine** [comment]
Since we're talking about coding patterns: I often code before breakfast, but I rarely connect to the internet before breakfast.

**Comment by episodeyang** [comment]
good pattern.
