### ISSUE TITLE
plyvel should accept memoryviews as keys and values

### ISSUE THREAD

**Issue by kyuupichan** [wbolster/plyvel#52]
I passed a memoryview to db.put() as the value, and I got an error

TypeError: Argument 'value' has incorrect type (expected bytes, got memoryview)

I doubt there is a good reason for this.  Can you accept memoryviews too please in all relevant APIs?  They enable me to avoid redundant copying of big binary objects when taking slices.

**Comment by wbolster** [comment]
there is no deliberate reason indeed.

but i think there could be some complexity. i think py2 and py3 work differently, and we're using cython.

feel free to suggest patches, or make a list of public api that would be touched by this.

(my time is limited. this is a spare time project.)

**Comment by wbolster** [comment]
@kyuupichan any chance you can test #53 and report back your findings?

**Comment by wbolster** [comment]
ping @kyuupichan 

i did some work on your request. your feedback would be appreciated.

**Comment by kyuupichan** [comment]
Sorry I have worked around the issue. In fact I am no longer using
memoryviews.
