### ISSUE TITLE
How can I get the version with the max_file_size for plyvel ?

### ISSUE THREAD

**Issue by wxcsdb88** [wbolster/plyvel#55]
I need the plyvel with the parameter max_file_size, but the plyvel 0.9 not has it. 
The [leveldb](https://github.com/rjpower/py-leveldb) in PyPI has been updated, now is [leveldb](https://pypi.python.org/pypi/leveldb/0.20)==0.20 with max_file_size. So I want to get the plyvel with the parameter max_file_size or guide me to solve it.
Thanks.

**Comment by wbolster** [comment]
this flag is not present in the header files on my system. i am not sure this can be added in a backwards compatible way...

**Comment by wxcsdb88** [comment]
@wbolster 
Thanks. I have solved it.
Clone the plyvel source code and add the max_file_size to plyvel._plyvel.pyx and leveldb.pxd.
Now, it seems ok.
