### ISSUE TITLE
plyvel and conda and bundle-leveldb branch

### ISSUE THREAD

**Issue by robdmc** [wbolster/plyvel#71]
Hello.

I've been able to get a build script going that I'm pretty sure I can work into a conda-installable package for plyvel.  I noticed, however, that you have a bundle-leveldb branch.  I was wondering what the status of that was.  If level-db were bundled, then a conda package becomes kind of irrelevant.

If you'd like a PR for some conda-friendly changes, let me know.  I think I can help with that.

**Comment by wbolster** [comment]
ah, that branch is really old and i lost interest, and i don't want to maintain leveldb snapshots.

with the recent plyvel 1.x series, binary wheel packages for linux are available from pypi, which solves the same ‘problem’ (no local leveldb library and development headers) in a clean and standard way.

**Comment by wbolster** [comment]
others have reported build problems on osx before (search the closed issues) but i think these eventually all boiled down to some environment issues.

i do not use osx myself so i can't help but point you to the other issues ;)

**Comment by robdmc** [comment]
Sounds good.  Thanks for the info  I'll play around with it when I have more time.  

Thank you for maintaining this package.

**Comment by wbolster** [comment]
thanks for telling me that; i appreciate it!
