### ISSUE TITLE
Usage inside a framework like Flask with debug mode raises Resource Unavailable Error

### ISSUE THREAD

**Issue by fingertap** [wbolster/plyvel#81]
The code is simple:
```python
from flask import Flask
import plyvel

app = Flask(__name__)
db = plyvel.DB("database/Users", create_if_missing=True)
app.run("0.0.0.0", debug=True)
```
If you add `debug=True` then the error is raised. Otherwise it's fine. But I think I should post this issue here so as you know.

**Comment by wbolster** [comment]
you did not share the error and backtrace.

are you sure you only use _ONE_ process, as LevelDB prescribes?

**Comment by fingertap** [comment]
The error message is shown as follows:
```python
Traceback (most recent call last):
  File "test.py", line 6, in <module>
    db_pool = plyvel.DB("./database/Users", create_if_missing=True)
  File "plyvel/_plyvel.pyx", line 247, in plyvel._plyvel.DB.__init__
  File "plyvel/_plyvel.pyx", line 88, in plyvel._plyvel.raise_for_status
plyvel._plyvel.IOError: b'IO error: lock ./database/Users/LOCK: Resource temporarily unavailable'
```
I guess the error may be the conflict when both `flask` watches the change in the directory and `plyvel` wants to write it.

**Comment by wbolster** [comment]
i think you're using multiple processes somehow, which leveldb _cannot_ do.  (not a plyvel limitation).

how do you run it?

**Comment by fingertap** [comment]
Just install the `flask` and `plyvel` and run the sample code like `python test.py`.
There must be another process when the framework "watches" the directory.
I don't know exactly why multiple processes raises such error, but I think the issue here can save others' time.

**Comment by wbolster** [comment]
the `debug=True` makes flask use werkzeug's autoreloader, which forks subprocesses.  as i said before:

> i think you're using multiple processes somehow, which leveldb cannot do. (not a plyvel limitation).

so that explain everything.

the module-level database opening is _not_ ok here. you'd be better off using a different pattern, such as those in the flask docs: http://flask.pocoo.org/docs/1.0/tutorial/database/
