### ISSUE TITLE
Guidance re compilation issue

### ISSUE THREAD

**Issue by brickinedifice** [wbolster/plyvel#83]
Hi. I get this issue when I try to compile plyvel.  Could you give me some guidance on how to troubleshoot this? Appreciate it. 

Thanks, DB. 

[log.txt](https://github.com/wbolster/plyvel/files/2334789/log.txt)

**Comment by brickinedifice** [comment]
Installed compilers using apt. 

I installed bitcoin which I believe has it’s own version of leveldb. Would that make a difference?

**Comment by wbolster** [comment]
no i don't think so.

try on a clean machine  (docker/vm whatever)  since it seems a problem with your toolchain.

also on linux the binary wheels can avoid compilation altogether.
