### ISSUE TITLE
Broken Import in Plyvel

### ISSUE THREAD

**Issue by ghost** [wbolster/plyvel#84]
I viewed error like this,
`No module named _plyvel`

i import package downloading plyvel folder in github,
please help

**Comment by wbolster** [comment]
this is not enough information. you don't describe what you did, and you don't describe what happened.

**Comment by wbolster** [comment]
also try reading the docs first?  just an idea.

**Comment by wbolster** [comment]
https://plyvel.readthedocs.io/en/latest/installation.html
