### ISSUE TITLE
max_file_size not working?

### ISSUE THREAD

**Issue by rongou** [wbolster/plyvel#87]
I'm trying to load a large db (~170GB, 24 million rows, each row is about 7KB) with these options:
```python
db = plyvel.DB(
    my_dir,
    create_if_missing=True,
    error_if_exists=True,
    write_buffer_size=1 << 30,
    max_open_files=50000,
    lru_cache_size=2 << 30,
    block_size=4 << 20,
    max_file_size=1 << 30)
```
but after a few write batches, I got tons of small files less than 1MB. If I leave out the `max_file_size` option, most files are around 4MB. Is this expected behavior? Seems to be similar to the issue reported in https://github.com/google/leveldb/issues/438.

**Comment by wbolster** [comment]
i don't know. plyvel does not do anything with that value except passing it along to leveldb.

but as you suggest yourself already, this is not a plyvel (python bindings) issue, so i'm not sure why you opened this issue here. ;)
