### ISSUE TITLE
idb_cmp1 does not match existing comparator : leveldb.BytewiseComparator

### ISSUE THREAD

**Issue by XVilka** [wbolster/plyvel#93]
When I open IndexedDB from Google Chrome:
```python
import plyvel
db = plyvel.DB('/home/<user>/.config/google-chrome/Default/IndexedDB/https_<site>_0.indexeddb.leveldb')
for key, value in db:
    print("{0} : {1}".format(key, value)) 
```
it returns the error:
```
Error: b'Invalid argument: idb_cmp1 does not match existing comparator : leveldb.BytewiseComparator'
```

Seems FastNoSQL project [met the same problem](https://github.com/fastogt/fastonosql/issues/24) and solved it.

**Comment by wbolster** [comment]
apparently that db does use a custom comparator. reimplementing it is the only way to make this work via plyvel. see docs for help and caveats.
